import {
  Award,
  Banknote,
  BadgeCheck,
  Bike,
  Blocks,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  Car,
  Clock,
  Cog,
  Droplet,
  Eye,
  Factory,
  Fuel,
  Gauge,
  GraduationCap,
  Hammer,
  Heart,
  Info,
  Landmark,
  Layers,
  Link2,
  Mail,
  MapPin,
  Maximize2,
  Package,
  Palette,
  Phone,
  Ruler,
  Scale,
  Settings2,
  Shirt,
  ShieldCheck,
  Sparkles,
  Store,
  Tag,
  Timer,
  Truck,
  User,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

const RULES = [
  [/price|سعر|cost|تكلفة|amount|مبلغ|جنيه|salary|راتب|deposit|مقدم/i, Banknote],
  [/view|مشاهد/i, Eye],
  [/like|إعجاب|favorite|مفضل/i, Heart],
  [/expire|انتهاء|remaining|متبق/i, Timer],
  [/date|تاريخ|year|سنة|createdat|updatedat|موسم|season/i, CalendarDays],
  [/time|وقت|hour|ساعة|duration|مدة|period/i, Clock],
  [/phone|هاتف|whatsapp|واتساب|mobile|موبايل/i, Phone],
  [/email|بريد/i, Mail],
  [/website|موقع الإلكتروني|url|link|رابط/i, Link2],
  [/governorate|محافظة|center|مركز|city|مدينة|address|عنوان|location|موقع/i, MapPin],
  [/kilometer|كيلومتر|mileage|عداد|power|قوة|speed|سرعة/i, Gauge],
  [/fuel|وقود|بنزين|ديزل/i, Fuel],
  [/transmission|ناقل الحركة|gear|engine|محرك|cc|ماكينة|machine/i, Cog],
  [/electric|كهرب|energy|طاقة/i, Zap],
  [/car|سيار|vehicle|مركب/i, Car],
  [/motorcycle|موتوسيكل|دراج/i, Bike],
  [/truck|نقل|delivery|توصيل|shipping|شحن/i, Truck],
  [/workshop|ورشة|craft|حرف|repair|صيانة|tool|أدوات/i, Wrench],
  [/handmade|يدوي|hammer|نجار|حداد/i, Hammer],
  [/factory|مصنع|production|إنتاج|manufactur|تصنيع/i, Factory],
  [/company|شركة|business|أعمال|employer|صاحب العمل/i, Building2],
  [/store|محل|shop|متجر|merchant|تاجر|supplier|مورد|selling|بيع/i, Store],
  [/job|وظيف|work|عمل|career|مهنة/i, Briefcase],
  [/education|مؤهل|degree|شهادة|training|تدريب|study|دراس/i, GraduationCap],
  [/experience|خبرة|level|مستوى/i, Award],
  [/color|لون/i, Palette],
  [/size|مقاس|حجم/i, Maximize2],
  [/weight|وزن|kg|كجم/i, Scale],
  [/height|ارتفاع|width|عرض|length|طول|area|مساحة|dimension|أبعاد/i, Ruler],
  [/material|خامة|metal|معدن|fabric|قماش/i, Layers],
  [/clothing|ملابس|shirt|تيشيرت|fashion|أزياء/i, Shirt],
  [/quantity|كمية|عدد|count|stock|مخزون/i, Boxes],
  [/feature|ميز|option|خيار/i, Sparkles],
  [/condition|حالة|status|وضع/i, BadgeCheck],
  [/warranty|ضمان|license|رخصة|ترخيص|insurance|تأمين|safe|أمان/i, ShieldCheck],
  [/health|صحة|vaccination|تحصين|treatment|علاج|water|مياه|cooling|تبريد/i, Droplet],
  [/owner|مالك|seller|بائع|user|مستخدم|applicant|متقدم|artist|فنان/i, User],
  [/gender|جنس|breed|سلالة|animal|حيوان|pet|أليف|type|نوع/i, Blocks],
  [/team|فريق|staff|موظف|member|عضو|group|مجموعة/i, Users],
  [/product|منتج|item|قطعة|package|طرد/i, Package],
  [/brand|ماركة|model|موديل|tag|علامة/i, Tag],
  [/bank|بنك|payment|دفع|finance|تمويل/i, Landmark],
  [/setting|إعداد|config|تهيئة|method|طريقة|purpose|غرض/i, Settings2],
];

export function pickFieldIcon(key = "", label = "") {
  const haystack = `${key} ${label}`;

  const match = RULES.find(([pattern]) => pattern.test(haystack));

  return match ? match[1] : Info;
}

export default pickFieldIcon;
